//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUProyecto
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Voluntario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voluntario()
        {
            this.Registro = new HashSet<Registro>();
        }
        [ScaffoldColumn(false)]
        public int idvoluntario { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Los nombres son requeridos"), MaxLength(55)]
        [Display(Name = "Nombres Voluntario")]
        public string nombres { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Los apellidos son requeridos"), MaxLength(55)]
        [Display(Name = "Apellidos Voluntario")]
        public string apellidos { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "La cedula es requerida"), MaxLength(55)]
        [Display(Name = "Cedula")]
        public string cedula { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "El telefono es requerido"), MaxLength(55)]
        [Display(Name = "Telefono")]
        public string telefono { get; set; }
        
        [Display(Name = "Fecha nacimiento")]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "La direccion es requerida"), MaxLength(55)]
        [Display(Name = "Direccion")]
        public string direccion { get; set; }
   
        [Display(Name = "Sexo")]
        public string sexo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registro> Registro { get; set; }
        public override string ToString()
        {
            return nombres + " " + apellidos;
        }
    }
}
